# coding: utf-8

"""
    Cleemy Expenses

    Welcome on the documentation for the CleemyExpenses API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items.post import CreateNewTemporaryExpenseRaw
from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items_expense_temp_item_id.get import GetByIdRaw
from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items.get import ListTempItemsRaw
from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items_expense_temp_item_id.put import UpdateExpenseTempItemRaw


class ExpensesApiRaw(
    CreateNewTemporaryExpenseRaw,
    GetByIdRaw,
    ListTempItemsRaw,
    UpdateExpenseTempItemRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
