# coding: utf-8

"""
    Cleemy Expenses

    Welcome on the documentation for the CleemyExpenses API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items.post import CreateNewTemporaryExpense
from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items_expense_temp_item_id.get import GetById
from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items.get import ListTempItems
from lucca_cleemy_expenses_python_sdk.paths.api_v3_expense_temp_items_expense_temp_item_id.put import UpdateExpenseTempItem
from lucca_cleemy_expenses_python_sdk.apis.tags.expenses_api_raw import ExpensesApiRaw


class ExpensesApi(
    CreateNewTemporaryExpense,
    GetById,
    ListTempItems,
    UpdateExpenseTempItem,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ExpensesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ExpensesApiRaw(api_client)
